#!/usr/bin/env perl
# Calculate lattice Green's function
# Input: chemical potential mu, self-energy Sigma (resigma.dat, imsigma.dat)
# Output: Green's function multiplied by -1/pi (imaw.dat, reaw.dat)
# Rok Zitko, rok.zitko@ijs.si, 2024-2026

use strict;
use warnings;

chomp(my $mu = `cat param.mu`);

system("hilb -v -d DOS.dat -x $mu res/resigma.dat res/imsigma.dat res/reaw.dat res/imaw.dat") == 0 or die "hilb failed: $?";
