#!/usr/bin/env perl
# Calculate lattice Green's function
# Input: chemical potential mu, self-energy Sigma (resigma.dat, imsigma.dat)
# Output: Green's function multiplied by -1/pi (imaw.dat, reaw.dat)
# Rok Zitko, rok.zitko@ijs.si, 2024-2026

use strict;
use warnings;

chomp(my $mu = `cat param.mu`);

# Clipping of Im part of GF; this can happen due to numerical integration for narrow regions of small ImSigma
chomp(my $imclip = `getparam clipG param.loop`);
if ($imclip eq "") {
  chomp($imclip = `getparam clip param.loop`); # fall back
}
$imclip ne "" or die;
$imclip > 0.0 or die;

print("bandDOS mu=$mu imclip=$imclip\n");

my $fntmp = "imaw.dat.TMP"; # before clipping

system("hilb -v -d DOS.dat -x $mu res/resigma.dat res/imsigma.dat res/reaw.dat $fntmp") == 0 or die "hilb failed: $?";

system("clipy b $imclip $fntmp >res/imaw.dat") == 0 or die;
unlink($fntmp);
