#!/usr/bin/env perl
# Calculate transport properties
# Warning: This scripts read Phi(epsilon) from a file
# Rok Zitko, rok.zitko@ijs.si, 2017-2026

use strict;
use warnings;
use FindBin;
use lib $FindBin::Bin;
use Bubble qw(bubble_options bubble_scalar chemical_potential parameter write_scalar);
use Math::Complex;

my $verbose = 1;

my $T = parameter("T");
$T > 0.0 or die "T must be positive\n";

my $factor = pi**2;
# pi^2 from the difference between A(w)=-1/Pi Im[..] and a(w)=-Im[..]

my $mu = chemical_potential();

my $fn = "PHI.dat"; # transport function
my @param = (bubble_options(epsabs => "1e-7", epsrel => "1e-8"), "-p", $fn);

my $res;
$res = bubble_scalar(@param, 0, 2, 0, $T, $mu, "resigma.dat", "imsigma.dat");
my $a0 = $factor*$res;
$res = bubble_scalar(@param, 0, 2, 1, $T, $mu, "resigma.dat", "imsigma.dat");
my $a1 = $factor*$res;
$res = bubble_scalar(@param, 0, 2, 2, $T, $mu, "resigma.dat", "imsigma.dat");
my $a2 = $factor*$res;

my $A0 = $a0*$T;
my $A1 = $a1;
my $A2 = $a2/$T;

if ($verbose) {
    print "a0=$a0\n";
    print "a1=$a1\n";
    print "a2=$a2\n";
    print "A0=$A0\n";
    print "A1=$A1\n";
    print "A2=$A2\n";
}

my $cond = $a0;
my $rho = 1/$cond;
my $thermo = -$A1/$A0;
my $kappa = $A2-$A1**2/$A0;
my $Lorentz = $A2/$A0;
my $ZT = $thermo**2 * $cond * $T / $kappa;

if ($verbose) {
    print "cond=$cond\n";
    print "rho=$rho\n";
    print "thermo=$thermo\n";
    print "kappa=$kappa\n";
    print "Lorentz=$Lorentz\n";
    print "ZT=$ZT\n";
}

write_scalar("condMIR.dat", $cond);
write_scalar("rhoMIR.dat", $rho);
write_scalar("thermopowerS.dat", $thermo);
write_scalar("kappa.dat", $kappa);
write_scalar("LL.dat", $Lorentz);
write_scalar("ZT.dat", $ZT);
