#!/usr/bin/env perl
# Calculate transport properties
# Warning: This scripts read Phi(epsilon) from a file
# Rok Zitko, rok.zitko@ijs.si, 2017-2026

use strict;
use warnings;
use Math::Complex;

my $verbose = 1;

chomp(my $T = `getparam T param.loop`);

my $factor = pi**2;
# pi^2 from the difference between A(w)=-1/Pi Im[..] and a(w)=-Im[..]

# Chemical potential
chomp(my $mu = `cat param.mu`);

my $fn = "PHI.dat"; # transport function
my $param = "-E -p $fn -c 30 -a 1e-7 -r 1e-6 -i 3 -k 6"; # numerical integration parameters

my $res;
$res = `bubble $param 0 2 0 $T $mu resigma.dat imsigma.dat`;
($? == 0) or die;
my $a0 = $factor*$res;
$res = `bubble $param 0 2 1 $T $mu resigma.dat imsigma.dat`;
($? == 0) or die;
my $a1 = $factor*$res;
$res = `bubble $param 0 2 2 $T $mu resigma.dat imsigma.dat`;
($? == 0) or die;
my $a2 = $factor*$res;

my $A0 = $a0*$T;
my $A1 = $a1;
my $A2 = $a2/$T;

if ($verbose) {
    print "a0=$a0\n";
    print "a1=$a1\n";
    print "a2=$a2\n";
    print "A0=$A0\n";
    print "A1=$A1\n";
    print "A2=$A2\n";
}

my $cond = $a0;
my $rho = 1/$cond;
my $thermo = -$A1/$A0;
my $kappa = $A2-$A1**2/$A0;
my $Lorentz = $A2/$A0;
my $ZT = $thermo**2 * $cond * $T / $kappa;

if ($verbose) {
    print "cond=$cond\n";
    print "rho=$rho\n";
    print "thermo=$thermo\n";
    print "kappa=$kappa\n";
    print "Lorentz=$Lorentz\n";
    print "ZT=$ZT\n";
}

system "echo $cond >condMIR.dat";
system "echo $rho >rhoMIR.dat";
system "echo $thermo >thermopowerS.dat";
system "echo $kappa >kappa.dat";
system "echo $Lorentz >LL.dat";
system "echo $ZT >ZT.dat";
