#!/usr/bin/env perl
# Check for the convergence of the DMFT calculation.
# Returns 0 if we need to continue, 1 if convergence is achieved.
# Rok Zitko, 2008-2026

use strict;
use warnings;
use Getopt::Long qw(GetOptions);

my ($iter, $fn, $decision_file);
$fn = "DIFFS_C";
GetOptions(
    "iteration=i" => \$iter,
    "diffs=s" => \$fn,
    "decision=s" => \$decision_file,
) or die "Invalid arguments.\n";

chomp(my $convergencelimit = `getparam conveps param.loop`);
chomp(my $convwindow = `getparam convwindow param.loop`);
chomp(my $miniter = `getparam miniter param.loop`);
chomp(my $maxiter = `getparam maxiter param.loop`);

die "Invalid convwindow=$convwindow. Stopped" if $convwindow < 1;

if (!defined $iter) {
    chomp($iter = `getiter`);
}
$iter =~ /\A\d+\z/ && $iter >= 1 or die "Invalid iteration: $iter\n";
print "checkconv, iter=$iter miniter=$miniter maxiter=$maxiter convwindow=$convwindow\n";

my $decision = "continue";
my $abs;
if ($iter > 1 && -e $fn) {
    open(my $fh, "<", $fn) or die "Can't open $fn: $!. Stopped";
    my @l = <$fh>;
    close($fh);

    if (@l >= $convwindow) {
        my $last = $l[-1];
        chomp($last);
        my ($iter2, $diff2) = split(' ', $last, 2);
        warn "Iteration number and $fn do not agree.\n" if $iter != $iter2;

        $abs = 0;
        foreach my $line (@l[-$convwindow .. -1]) {
            chomp($line);
            my ($iter3, $diff3) = split(' ', $line, 2);
            my $a = abs($diff3);
            $abs = $a if $a > $abs;
        }

        if ($abs < $convergencelimit && $iter > $miniter) {
            print "Convergence achieved! $abs < $convergencelimit\n";
            $decision = "converged";
        } else {
            print "Not converged yet. $abs > $convergencelimit\n";
            if ($iter > $maxiter) {
                print "Iteration limit exceeded, maxiter=$maxiter, stopping here.\n";
                $decision = "stop";
            }
        }
    }
}

if (defined $decision_file) {
    open(my $out, ">", $decision_file) or die "Can't write $decision_file: $!";
    print $out "$decision\n";
    close($out) or die "Can't close $decision_file: $!";
} elsif ($decision eq "converged") {
    system("touch", "CONVERGED") == 0 or die "Can't create CONVERGED: $?";
    system("scripts/cleanup_temp") == 0 or warn("cleanup_temp failed");
    system("scripts/post") == 0 or warn("Running scripts/post failed");
} elsif ($decision eq "stop") {
    system("touch", "STOP") == 0 or die "Can't create STOP: $?";
}
