#!/bin/bash
# Clean up after the calculation; this one deletes various temporary files, but keeps output files from the calculation.
# This script does not delete any files that are required for continuing the DMFT iteration.
# Rok Zitko, Aug 2026

# Template initialization
rm -f ham ham.* mat mat.res val vec vec.* xi1.dat zeta1.dat theta1.dat
rm -f data
rm -f param.param param.extra param.dmft param

# Mesh refinement
rm -f logNEW* logUNION* log.resample
rm -f ReDelta*NEW* ReDelta*OLD* ReDelta*TEMP
rm -f ImDelta*NEW* ImDelta*OLD* ImDelta*TEMP
rm -f Delta*NEW* Delta*OLD* Delta*TEMP Delta*.raw
rm -f ReDelta*.validate-kk.*

# Temporary directories
delete_NRG_output

# Slurm logs
rm -f slurm-*.out

# Other temporaries
rm -rf imaw.dat.prev
rm -rf .occupancy-* res/.occupancy-*
