#!/bin/bash
# Clean up after the calculation; this removes all output. If command line argument "keep" is used,
# ImDelta.dat and ReDelta.dat will be retained to enable restarting the calculation (param.mu is never deleted)
# Rok Zitko, Aug 2026

scripts/cleanup_temp

if [[ "$1" != "keep" ]]; then
  rm -f ImDelta.dat ReDelta.dat
fi

rm -fr res/ dmft/

# Dynamical quantities
rm -f Delta.dat imaw.dat reaw.dat imaw.dat.prev imsigma.dat resigma.dat self.dat
# ReDelta shift
rm -f param.shift
# Expectation values
rm -f custom custom.avg customfdm customfdm.avg
# Occupancy control
rm -f occupancy.log occupancy.control.log
# Transport
rm -f LL.dat ZT.dat condMIR.dat rhoMIR.dat cond.opt-PHI.dat ekin.dat kappa.dat thermopowerS.dat # transport
# Band discretization
rm -f FSOL.dat FSOLNEG.dat
# Frequency mesh
rm -f mesh.dat
# Alt lattice spectral funciton
rm -f ldos.dat
# Flag files, loop control
rm -f CONVERGED STOP ITER DIFFS_C DIFFS_LatLoc
