#!/usr/bin/env perl
# Copy the (processed) results of the current NRG iteration.
# Rok Zitko, rok.zitko@ijs.si, 2008-2026

use strict;
use warnings;
use File::Copy;

my $iter = `getiter`;

# Note: For Broyden mixing (if implemented), $track must be 1.
my $track = 1; # 0=do not store copies in dmft/, 1=track DMFT iteration by storing copies of all results in dmft/.

chomp(my $tr = `getparam track param.loop`);
$track = ($tr eq "true")  ? 1 : 0;

sub cp {
    my $fn = shift;
    if ($track) { copy("res/$fn", "dmft/$iter-$fn")
      or die "Copying $fn failed: $!, stopped"; }
}

sub cp0 {
    my $fn = shift;
    if ($track) { copy("$fn", "dmft/$iter-$fn")
      or warn "Warning: Copying solverlog failed: $!"; }
}

sub cp1 {
    my $fn = shift;
    if ($track) { copy("1/$fn", "dmft/$iter-$fn")
      or warn "Warning: Copying solverlog failed: $!"; }
}

system("mkdir -p dmft") == 0 or die; # Ensure dmft/ exists.

# Whatever spectral functions we are interested in.
cp("c-imG.dat");
cp("c-self.dat");

# The following are *required* for the DMFT loop
cp("imsigma.dat");
cp("resigma.dat");
cp("imaw.dat");
cp("reaw.dat");

# Best-so-far results for post-processing.
system("cp -v res/imsigma.dat imsigma.dat") == 0 or die;
system("cp -v res/resigma.dat resigma.dat") == 0 or die;
if (-s "imaw.dat") {
    system("cp -v imaw.dat imaw.dat.prev") == 0 or die;
} # store previous version, for use in script diffs
system("cp -v res/imaw.dat imaw.dat") == 0 or die;
system("cp -v res/reaw.dat reaw.dat") == 0 or die;
system("cp -v res/c-self.dat self.dat") == 0 or die;

# NRG iteration logs, etc.
cp1("custom");
cp1("log");
cp1("td");

# Expectation values
cp0("custom");
cp0("custom.avg");
cp0("customfdm");
cp0("customfdm.avg");

if ($track) { copy("Delta.dat", "dmft/$iter-Delta.dat")
  or warn "Warning: Copying Delta failed: $!"; }
