#!/usr/bin/env perl
# Calculate differences between successive iterations.
# Rok Zitko, 2008-2026

use strict;
use warnings;

my $iter = `getiter`;

diff("imaw", "DIFFS_C");  ### IMPORTANT: use imaw here !!

sub diff {
 return if ($iter == 1);
 my $previous = $iter-1;

 my $what = shift;
 my $output = shift;

 my $fn1 = "$what.dat";
 my $fn2 = "$what.dat.prev";

 -s $fn1 or die "$fn1 does not exist. Stopped";
 -s $fn2 or die "$fn2 does not exist. Stopped";

 # Support for adaptive mesh
 system("resample $fn1 mesh.dat $fn1.tmp") == 0 or die "resample failed: $?";
 system("resample $fn2 mesh.dat $fn2.tmp") == 0 or die "resample failed: $?";

 chomp(my $diff = `subtracty $fn1.tmp $fn2.tmp | integrateabs`);
 print "diff($fn1 - $fn2)=$diff\n";
 $diff != "" or die "Calculation of diff failed.";
 $diff != 0 or die "Difference is exactly zero. This is very suspicious. Stopping";

 # NOTE: This is simply an integral of A(w) from -inf to 0, so it only corresponds to occupancy
 # in the zero-temperature case. This value is reported for debugging purposes, it is not used
 # otherwise.
 chomp(my $occupancydiff = `subtracty $fn1.tmp $fn2.tmp | integratenegabs`);
 print "occupancy diff=$occupancydiff\n";

 unlink("$fn1.tmp", "$fn2.tmp");

 open(OUT, ">>$output") or die "Can't append to $output: $!. Stopped";
 print OUT "$iter $diff\n";
 close OUT;
}
