#!/usr/bin/env perl
# Calculate differences between successive iterations.
# Rok Zitko, 2008-2026

use strict;
use warnings;
use Getopt::Long qw(GetOptions);
use File::Spec;

my ($iter, $current, $previous, $local, $mesh, $output_dir);
$current = "imaw.dat";
$previous = "imaw.dat.prev";
$local = "res/c-self.dat";
$mesh = "mesh.dat";
$output_dir = ".";
GetOptions(
    "iteration=i" => \$iter,
    "current=s" => \$current,
    "previous=s" => \$previous,
    "local=s" => \$local,
    "mesh=s" => \$mesh,
    "output-dir=s" => \$output_dir,
) or die "Invalid arguments.\n";

if (!defined $iter) {
    chomp($iter = `getiter`);
}
$iter =~ /\A\d+\z/ && $iter >= 1 or die "Invalid iteration: $iter\n";
-d $output_dir or die "Output directory not found: $output_dir\n";

diff($current, $previous, File::Spec->catfile($output_dir, "DIFFS_C"));
diff($current, $local, File::Spec->catfile($output_dir, "DIFFS_LatLoc"));

sub diff {
 return if ($iter == 1);
 my $fn1 = shift;
 my $fn2 = shift;

 -s $fn1 or die "$fn1 does not exist. Stopped";
 -s $fn2 or die "$fn2 does not exist. Stopped";

 my $output = shift;

 # Support for adaptive mesh
  my $tmp1 = File::Spec->catfile($output_dir, ".diff-1.tmp");
  my $tmp2 = File::Spec->catfile($output_dir, ".diff-2.tmp");
  my $residual = File::Spec->catfile($output_dir, ".diff-residual.tmp");
  unlink($tmp1, $tmp2, $residual);
  my @resample = ("resample", "--interpolation", "steffen", "-p", "17");
  system(@resample, $fn1, $mesh, $tmp1) == 0 or die "resample failed: $?";
  system(@resample, $fn2, $mesh, $tmp2) == 0 or die "resample failed: $?";

  write_difference($tmp1, $tmp2, $residual);
  my $diff = command_output(
      "integ", "--interpolation", "steffen",
      "--epsabs", "1e-10", "--epsrel", "1e-9",
      "--workspace-limit", "1000", "--quadrature-rule", "61",
      "--gsl-error-policy", "fail", "-a", $residual,
  );
  chomp($diff);
 print "diff($fn1 - $fn2)=$diff\n";
 $diff ne "" or die "Calculation of diff failed.";

  # Additional negative-frequency L1 diagnostic; not used for convergence.
  my $negative_diff = command_output("integratenegabs", $residual);
  chomp($negative_diff);
 print "negative-frequency diff=$negative_diff\n";

  unlink($tmp1, $tmp2, $residual);

  my @old;
  if (-e $output) {
      open(my $in, "<", $output) or die "Can't read $output: $!. Stopped";
      @old = grep { (split)[0] ne "$iter" } <$in>;
      close($in);
  }
  open(my $out, ">", $output) or die "Can't write $output: $!. Stopped";
  print $out @old;
  print $out "$iter $diff\n";
  close($out) or die "Can't close $output: $!. Stopped";
}

sub write_difference {
  my ($first, $second, $output) = @_;
  open(my $input, "-|", "subtracty", $first, $second)
      or die "Can't run subtracty: $!";
  open(my $destination, ">", $output) or die "Can't write $output: $!";
  while (<$input>) {
      print {$destination} $_ or die "Can't write $output: $!";
  }
  close($input) or die "subtracty failed: $?";
  close($destination) or die "Can't close $output: $!";
}

sub command_output {
  my @command = @_;
  open(my $fh, "-|", @command) or die "Can't run $command[0]: $!";
  local $/;
  my $output = <$fh>;
  close($fh) or die "$command[0] failed: $?";
  defined($output) or die "$command[0] produced no output";
  return $output;
}
