#!/usr/bin/env perl
# Start the DMFT calculation by running this script!
# Rok Zitko, rok.zitko@ijs.si, 2022-2026

use strict;
use warnings;

my $mma = 0; # 0=instantiate (stand-alone), 1=nrginit (Mathematica)
my $local = 1; #0=submit a Slurm job, 1=run locally

-e "DOS.dat" or die "Tabulated density of states DOS.dat must exist.";

if (!-e "Delta.dat") {
    system("scripts/dmft_init") == 0 or die "dmft_init failed: $?";
}

my $Nz = `getparam Nz param.loop`;
chomp($Nz);

# Chemical potential
my $mu = `cat param.mu`;
chomp($mu);

# epsilon_d
my $eps = `cat param.eps`;
chomp($eps);

my $epsimp = $eps-$mu;

# Perform the discretization
system("m4 -DEPS=$epsimp -DZZZ=1 param.loop >param") == 0 or die "m4 failed: $?";
unlink "FSOL.dat"; # Delete first, avoid check passing with stale data.
unlink "FSOLNEG.dat";
system("adapt P >solverlog") == 0 or die "adapt failed: $?";
system("adapt N >solverlogneg") == 0 or die "adapt failed: $?";
(-s "FSOL.dat" && -s "FSOLNEG.dat") or die "solver failed.\n";
unlink "param";

# Run Nz instances of NRG iteration
for (my $i = 1; $i <= $Nz; $i++) {
  my $z = $i/$Nz;
  system("m4 -DEPS=$epsimp -DZZZ=$z param.loop >param") == 0 or die "m4 failed: $?";
  system("mkdir -p $i") == 0 or die "mkdir failed: $?";

  if ($mma) {
      chdir $i;
      system "cp ../Delta.dat Delta.dat";
      system "cp ../param param";
      system("nrginit")== 0 or die "nrginit failed: $?";
  } else {
      system("scripts/instantiate $i") == 0 or die "instantiate failed: $?";
      chdir $i;
  }

  if ($local) {
    system("mynrgrun") == 0 or die "nrg failed: $?";
  } else {
    system("subslurm") == 0 or die "subslurm failed: $?";
  }
  chdir "..";
}

# Process the results.
if (-x "scripts/dmft_done") {
    system("scripts/dmft_done") == 0 or die "dmft_done failed: $?";
}
