#!/usr/bin/env perl
# dmft_init - prepare a new DMFT run
# Rok Zitko, 2008-2026

use strict;
use warnings;

if (!-d "dmft") {
  mkdir "dmft" or die "Can't create subdir dmft, stopped";
}

if (!-d "res") {
    mkdir "res" or die "Can't create subdir res, stopped";
}

-s "param.mu" or die "Chemical potential param.mu not found.";
-s "param.loop" or die "Parameter file param.loop not found.";

if (-s "ReDeltaFirst.dat" && -s "ImDeltaFirst.dat") {
    # Preexisting initial approximation for hybridization function Delta(z)
    system("cp ReDeltaFirst.dat ReDelta.dat") == 0 or die;
    system("cp ImDeltaFirst.dat ImDelta.dat") == 0 or die;
    if (!-s "mesh.dat") {
        # Ensure mesh.dat is consistent with the mesh used in *DeltaFirst.dat
        system("cp ReDelta.dat mesh.dat") == 0 or die;
    }
} else {
    if (!-s "mesh.dat") {
      # If the mesh is not predefined, generate it using settings from param.loop
      system("scripts/init_mesh >mesh.dat") == 0 or die "init_mesh failed: $?";
    }
    # Generate imsigma.dat, resigma.dat
    system("scripts/init_Sigma") == 0 or die;
    # Generate lattice Green's function approx, reaw.dat, imaw.dat
    system("scripts/bandDOS") == 0 or die;
    # Generate hybridization function, ReDelta.dat, ImDelta.dat
    system("scripts/dmftDOS") == 0 or die;
}

-s "ReDelta.dat" or die;
-s "ImDelta.dat" or die;

sub read_number {
    my ($file) = @_;
    open my $fh, '<', $file or die "Cannot open '$file': $!";
    local $/; my $s = <$fh>;
    $s =~ s/^\s+|\s+$//g;
    $s =~ /\A[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?\z/
        or die "Invalid numeric value in '$file': '$s'";
    return 0 + $s;
}
