#!/usr/bin/env perl
# Script that runs after the iteration is finished
# Rok Zitko, 2008-2026

use strict;
use warnings;
use Term::ANSIColor qw(:constants);

my $mesh_refinement = 1; # 0=fixed mesh; 1=automatically refined mesh

my $Nz = `getparam Nz param.loop`;
chomp($Nz);

my $done = 0;
while (!$done) {
    # Check if the calculations are completed
    $done = 1;
    for (my $i = 1; $i <= $Nz; $i++) {
        my $dir = "$i";
        system "ls $dir"; # Help with refreshing file-system cache
        if (!-e "$dir/DONE") {
            print "Not done: $dir\n";
            $done = 0;
        }
    }

    print "Nz=$Nz done=$done\n";
    if (!$done) { sleep 60; }
}

system("mkdir -p res") == 0 or die;

# Clean up first: note, we explicitly list the files to be deleted!
system("rm -f res/*") == 0 or die;

# Store a copy of Hybridisation function *used* in the calculation in res/. The idea is that all files in res/ are consistent as regards
# the frequency grid, e.g., after running average and realparts, to have a consistent input for sigmatrick script.
system("cp -v ReDelta.dat res/ReDelta.dat") == 0 or die;
system("cp -v ImDelta.dat res/ImDelta.dat") == 0 or die;
# We also store param.mu that was *used* in the impurity solver (param.mu will be shifted by occupancy control!).
system("cp -v param.mu    res/param.mu") == 0 or die;
# Note that at the end of dmft_done, res/ contains *used* files, while ./ contains files for *next* iteration.

# Average spectral functions
msg("average");
system("scripts/average") == 0 or die "average failed: $?";

(-s "res/c-imF.dat" && -s "res/c-imG.dat")
or error("Spectral functions not found, stopped");

# Compute real parts
msg("realparts");
system("scripts/realparts") == 0 or die "realparts failed: $?";

(-s "res/c-reF.dat" && -s "res/c-reG.dat")
or error("Real parts of Green's functions not found, stopped");

# Expectation values
system("gatherlastlines custom") == 0 or die;
system("columnavg_comment custom >custom.avg") == 0 or die;
system("gatherlastlines customfdm") == 0 or die;
system("columnavg_comment customfdm >customfdm.avg") == 0 or die;

# Compute self-energy
msg("sigmatrick");
system("scripts/sigmatrick") == 0 or die "sigmatrick failed: $?";

(-s "res/imsigma.dat" && -s "res/resigma.dat")
or error("Self-energy not found, stopped");

# Compute G_script
msg("bandDOS");
system("scripts/bandDOS") == 0 or die "bandDOS failed: $?";

(-s "res/imaw.dat" && -s "res/reaw.dat")
or error("(Lattice) spectral functions not found, stopped");

# Increase iteration number (0 -> 1 initially); must be called before copyresults
msg("newiter");
system("newiter") == 0 or die "newiter failed: $?";

# Copy results of postprocessing. This generates copies in dmft/ (if configured to do so using $track=1)
# and in current directory (reaw.dat, imaw.dat, resigma.dat, imsigma.dat, DeltaLast.dat)
msg("copyresults");
system("scripts/copyresults") == 0 or die "copyresults failed: $?";

# Compute differences (for self-consistency condition checks)
msg("diffs");
system("scripts/diffs") == 0 or die "diffs failed: $?";

# We check for convergence at this point. This will generate CONVERGED flag file
# if the convergence criterium is reached. Also, the postprocessing scripts will run at
# this point. This is appropriate, since param.mu contains the chemical potential corresponding
# to current resigma.dat and imsigma.dat result files. (The value is updated by occupancy control
# just below.)
system("scripts/checkconv") == 0 or die "checkconv failed: $?";

## Start preparing input for the next iteration

# Occupancy control
msg("occupancy_control");
system("scripts/occupancy_control >occupancy.control.log 2>&1") == 0 or die "occupacy_control failed: $?";

# Compute hybridization function ImDelta.dat, ReDelta.dat
msg("dmftDOS");
system("mv ReDelta.dat ReDelta.dat.OLD") == 0 or die; # save the old ones!
system("mv ImDelta.dat ImDelta.dat.OLD") == 0 or die;
-s "ReDelta.dat.OLD" or die "Failed to create ReDelta.dat.OLD";
-s "ImDelta.dat.OLD" or die "Failed to create ImDelta.dat.OLD";
system("scripts/dmftDOS") == 0 or die "dmftDOS failed: $?"; # This produces new ImDelta.dat, ReDelta.dat
(-s "ImDelta.dat" && -s "ReDelta.dat") or error("dmftDOS failed, output files not found, stopped");
system("mv ReDelta.dat ReDelta.dat.NEW") == 0 or die;
system("mv ImDelta.dat ImDelta.dat.NEW") == 0 or die;

if ($mesh_refinement) {
    # Refine the mesh
    chomp(my $delta = `getparam opt_delta param.loop`);
    chomp(my $mindx = `getparam opt_mindx param.loop`);
    chomp(my $ymin  = `getparam opt_ymin  param.loop`);
    print "mesh optimization with delta=$delta mindx=$mindx ymin=$ymin\n";
    system("optimize_mesh ImDelta.dat.NEW $delta $mindx $ymin >ImDelta.dat.NEW-opt 2>logNEW") == 0 or die;
    system("mesh_union ImDelta.dat.OLD ImDelta.dat.NEW-opt >mesh.dat 2>logUNION") == 0 or die;
    # Resampling
    system("resample ReDelta.dat.OLD mesh.dat     ReDelta.dat.OLD-common") == 0 or die;
    system("resample ReDelta.dat.NEW mesh.dat     ReDelta.dat.NEW-common") == 0 or die;
    system("resample ImDelta.dat.OLD mesh.dat     ImDelta.dat.OLD-common") == 0 or die;
    system("resample ImDelta.dat.NEW mesh.dat     ImDelta.dat.NEW-common") == 0 or die;

    my $iter = `getiter`;
    system "cp logNEW logNEW.$iter";
    system "cp logUNION logUNION.$iter";
} else {
    print "Mesh refinement disabled.\n";
    system("cp ReDelta.dat.OLD ReDelta.dat.OLD-common") == 0 or die;
    system("cp ReDelta.dat.NEW ReDelta.dat.NEW-common") == 0 or die;
    system("cp ImDelta.dat.OLD ImDelta.dat.OLD-common") == 0 or die;
    system("cp ImDelta.dat.NEW ImDelta.dat.NEW-common") == 0 or die;
}

# Mixing of hybridization function
chomp(my $alpha = `getparam alpha param.loop`);
print "alpha=$alpha\n";
(0.0 <= $alpha && $alpha <= 1.0) or die "alpha is zero; 0<=alpha<=1";
my $f1 = $alpha;
my $f2 = 1.0-$alpha;
system("mixy $f1 ReDelta.dat.NEW-common $f2 ReDelta.dat.OLD-common >ReDelta.dat.TEMP") == 0 or die;
-s "ReDelta.dat.TEMP" or die "ReDelta Mixing failed.";
system("mixy $f1 ImDelta.dat.NEW-common $f2 ImDelta.dat.OLD-common >ImDelta.dat.TEMP") == 0 or die;
-s "ImDelta.dat.TEMP" or die "ImDelta Mixing failed.";

# Clipping of the hybridization function
chomp(my $imclip = `getparam clipDelta param.loop`);
if ($imclip eq "") {
    chomp($imclip = `getparam clip param.loop`); # fall back
}
$imclip ne "" or die;
$imclip > 0.0 or die;
print "imclip=$imclip\n";
system("clipy t -$imclip ImDelta.dat.TEMP >ImDelta.dat") == 0 or die;
-s "ImDelta.dat" or die "Clipping failed.";
system("cp ReDelta.dat.TEMP ReDelta.dat"); # just copy, no other processing
-s "ReDelta.dat" or die "Copying failed.";

# Remove 1/, 2/, etc.
msg("delete_NRG_output");
system("delete_NRG_output") == 0 or die;

# RECURSION!
# Note that if we stop at this point, the calculation can be continued by running DMFT, because the input (Delta.dat)
# is already prepared (mixing, etc.).
if (!-e "CONVERGED" && !-e "STOP") {
  system("scripts/DMFT") == 0 or die "DMFT failed: $?";
}

sub msg
{
    my $msg = shift;
    print RED, "$msg\n", RESET;
}

sub error
{
    my $msg = shift;
    open(F, ">ERROR") or die "Can't create an ERROR flag file, stopped";
    print F "Error: $msg\n";
    close(F);
    die $msg;
}
