#!/usr/bin/env perl
# Calculation of the effective hybridisation function using Delta=F_local/G_local
# Rok Zitko, rok.zitko@ijs.si, 2026

use strict;
use warnings;
use File::Basename qw(dirname);
use File::Spec;
use Math::Complex;

my $result_dir = @ARGV ? shift @ARGV : "res";
my $mu_file = @ARGV ? shift @ARGV : "param.mu";
my $re_output = @ARGV ? shift @ARGV : "ReDelta.dat";
my $im_output = @ARGV ? shift @ARGV : "ImDelta.dat";
@ARGV and die "Usage: $0 [result_dir [mu_file [re_output [im_output]]]]\n";

# Read a column from a file
sub readcol {
    my ($filename, $column) = @_;

    my @l;
    open(F, "<$filename") or die "Can't open $filename for reading, stopped";
    while (<F>) {
        chomp;
        my $x = (split)[$column-1];
        push(@l, $x);
    }
    close(F);

    @l
};

# Clipping of Im part of Delta; NRG requires Gamma=-Im(Delta) to be strictly positive.
chomp(my $imclip = `getparam clipDelta param.loop`);
if ($imclip eq "") {
    chomp($imclip = `getparam clip param.loop`); # fall back
}
$imclip ne "" or die;
$imclip > 0.0 or die;

chomp(my $sigma_clip = `getparam clipSigma param.loop`);
if ($sigma_clip eq "") {
    chomp($sigma_clip = `getparam clip param.loop`); # fall back
}
$sigma_clip ne "" or die;
$sigma_clip > 0.0 or die;

# Chemical potential
open(my $mu_fh, "<", $mu_file) or die "Can't open $mu_file for reading, stopped";
my $mu = <$mu_fh>;
close($mu_fh);
defined $mu or die "Chemical potential not found in $mu_file";
chomp($mu);

print "dmftDOS-stable - mu=$mu imclip=$imclip sigma_clip=$sigma_clip\n";

my $prefix = "$result_dir/";
my $reGtmp = "$result_dir/reG.dat.TMP";
my $imGtmp = "$result_dir/imG.dat.TMP";
my $reFtmp = "$result_dir/reF.dat.TMP";
my $imFtmp = "$result_dir/imF.dat.TMP";
my $re_target = output_target($re_output);
my $im_target = output_target($im_output);
my $re_publish = "$re_target.tmp.$$";
my $im_publish = "$im_target.tmp.$$";
END {
    unlink(grep { defined($_) && -e $_ }
           ($reGtmp, $imGtmp, $reFtmp, $imFtmp, $re_publish, $im_publish));
}
unlink($reGtmp, $imGtmp, $reFtmp, $imFtmp);

# Evaluate G_local and F_local at the same chemical potential. Without -G,
# hilb stores both with the same factor -1/pi, which cancels in their ratio.
system("hilb", "-v", "-i", "steffen", "-n", "0", "-d", "DOS.dat", "-x", $mu,
       "-c", $sigma_clip, "-f", "1e-12",
       "${prefix}resigma.dat", "${prefix}imsigma.dat", $reGtmp, $imGtmp)
    == 0 or die "hilb failed: $?";
system("hilb", "-v", "-i", "steffen", "-n", "1", "-d", "DOS.dat", "-x", $mu,
       "-c", $sigma_clip, "-f", "1e-12",
       "${prefix}resigma.dat", "${prefix}imsigma.dat", $reFtmp, $imFtmp)
    == 0 or die "hilb failed: $?";

my @omega = readcol($imGtmp, 1);
my @reGomega = readcol($reGtmp, 1);
my @imFomega = readcol($imFtmp, 1);
my @reFomega = readcol($reFtmp, 1);
my @imG =   readcol($imGtmp, 2);
my @reG =   readcol($reGtmp, 2);
my @imF =   readcol($imFtmp, 2);
my @reF =   readcol($reFtmp, 2);

scalar(@omega) == scalar(@imG) or die "ImG mesh mismatch.";
scalar(@omega) == scalar(@reG) or die "ReG mesh mismatch.";
scalar(@omega) == scalar(@imF) or die "ImF mesh mismatch.";
scalar(@omega) == scalar(@reF) or die "ReF mesh mismatch.";
for (my $i = 0; $i < @omega; ++$i) {
    $omega[$i] == $reGomega[$i] or die "ReG frequency mismatch.";
    $omega[$i] == $imFomega[$i] or die "ImF frequency mismatch.";
    $omega[$i] == $reFomega[$i] or die "ReF frequency mismatch.";
}

open(R, ">", $re_publish) or die "Can't write $re_publish: $!";
open(I, ">", $im_publish) or die "Can't write $im_publish: $!";

my $len = @omega;
for (my $i = 0; $i < $len; $i++) {
    my $o = $omega[$i];
    my $G = $reG[$i] + i * $imG[$i];
    my $F = $reF[$i] + i * $imF[$i];

    # Stable hybridisation-function estimator.
    my $Delta = $F/$G;
    my $re = Re($Delta);
    my $im = Im($Delta);
    abs($re) <= 1.7976931348623157e308
        && abs($im) <= 1.7976931348623157e308
        or die "Non-finite hybridization at frequency $o\n";

    if ($im > -$imclip) {
        $im = -$imclip;
    }
    $im < 0.0 or die; # contract

    print R "$o $re\n";
    print I "$o $im\n";
}

close(R) or die "Can't close $re_publish: $!";
close(I) or die "Can't close $im_publish: $!";
rename($re_publish, $re_target) or die "Can't replace $re_target: $!";
rename($im_publish, $im_target) or die "Can't replace $im_target: $!";

sub output_target {
    my ($path) = @_;
    return $path unless -l $path;
    my $target = readlink($path);
    defined($target) or die "Can't read output symlink $path: $!";
    return $target if File::Spec->file_name_is_absolute($target);
    return File::Spec->catfile(dirname($path), $target);
}
