#!/usr/bin/env perl
# Calculation of the effective hybridisation function
# Rok Zitko, rok.zitko@ijs.si, 2026

use strict;
use warnings;
use Math::Complex;

my $result_dir = @ARGV ? shift @ARGV : "res";
my $mu_file = @ARGV ? shift @ARGV : "param.mu";
my $gamma_output = @ARGV ? shift @ARGV : "Delta.raw.dat";
@ARGV and die "Usage: $0 [result_dir [mu_file [GammaOutput]]]\n";

# Read a column from a file
sub readcol {
    my ($filename, $column) = @_;

    my @l;
    open(F, "<$filename") or die "Can't open $filename for reading, stopped";
    while (<F>) {
        chomp;
        my $x = (split)[$column-1];
        push(@l, $x);
    }
    close(F);

    @l
};

my $pi = pi;

print "dmftDOS\n";

# Chemical potential
open(my $mu_fh, "<", $mu_file) or die "Can't open $mu_file for reading, stopped";
my $mu = <$mu_fh>;
close($mu_fh);
defined $mu or die "Chemical potential not found in $mu_file";
chomp($mu);

my $prefix = "$result_dir/";
my @omega = readcol("${prefix}imaw.dat", 1);
my @imG =   readcol("${prefix}imaw.dat", 2);
my @reG =   readcol("${prefix}reaw.dat", 2);
my @imS =   readcol("${prefix}imsigma.dat", 2);
my @reS =   readcol("${prefix}resigma.dat", 2);

scalar(@omega) == scalar(@imG) or die "ImG mesh mismatch.";
scalar(@omega) == scalar(@reG) or die "ReG mesh mismatch.";
scalar(@omega) == scalar(@imS) or die "ImSigma mesh mismatch.";
scalar(@omega) == scalar(@reS) or die "ReSigma mesh mismatch.";

open(my $gamma_fh, ">", $gamma_output) or die;

my $len = @omega;
for (my $i = 0; $i < $len; $i++) {
    my $o = $omega[$i];
    my $G = $reG[$i] + i * $imG[$i];
    my $sigma = $reS[$i] + i * $imS[$i];
    my $GF = -$pi * $G; # difference between DOS and Im GF !
    Im($sigma) < 0.0 or die; # contract
    Im($GF) < 0.0 or die; # contract

    # G_0^-1 = G^-1_local + Sigma
    my $g01 = 1/$GF + $sigma;

    # Delta(z) = z+mu-G_0^-1
    my $Delta = $o + $mu - $g01;

    my $gamma = -Im($Delta);
    print {$gamma_fh} "$o $gamma\n";
}
close($gamma_fh) or die "Can't close $gamma_output: $!";
