#!/usr/bin/env perl
# Calculation of the effective hybridisation function
# Rok Zitko, rok.zitko@ijs.si, 2026

use strict;
use warnings;
use Math::Complex;

# Read a column from a file
sub readcol {
    my ($filename, $column) = @_;

    my @l;
    open(F, "<$filename") or die "Can't open $filename for reading, stopped";
    while (<F>) {
        chomp;
        my $x = (split)[$column-1];
        push(@l, $x);
    }
    close(F);

    @l
};

my $pi = pi;

chomp(my $clip = `getparam clip param.loop`);
print "dmftDOS - clip=$clip\n";

# Chemical potential
my $mu = `cat param.mu`;
chomp($mu);

my $prefix = "res/";
my @omega = readcol("${prefix}imaw.dat", 1);
my @imG =   readcol("${prefix}imaw.dat", 2);
my @reG =   readcol("${prefix}reaw.dat", 2);
my @imS =   readcol("${prefix}imsigma.dat", 2);
my @reS =   readcol("${prefix}resigma.dat", 2);

scalar(@omega) == scalar(@imG) or die "ImG mesh mismatch.";
scalar(@omega) == scalar(@reG) or die "ReG mesh mismatch.";
scalar(@omega) == scalar(@imS) or die "ImSigma mesh mismatch.";
scalar(@omega) == scalar(@reS) or die "ReSigma mesh mismatch.";

# Important: this writes ReDelta.dat and ImDelta.dat in the current directory.
# It does *not* overwrite res/ReDelta.dat and res/ImDelta.dat.
open(R, ">ReDelta.dat") or die;
open(I, ">ImDelta.dat") or die;

my $len = @omega;
for (my $i = 0; $i < $len; $i++) {
    my $o = $omega[$i];
    my $G = $reG[$i] + i * $imG[$i];
    my $sigma = $reS[$i] + i * $imS[$i];
    my $GF = -$pi * $G; # difference between DOS and Im GF !

    # G_0^-1 = G^-1_local + Sigma
    my $g01 = 1/$GF + $sigma;

    # Delta(z) = z+mu-G_0^-1
    my $Delta = $o + $mu - $g01;

    my $re = Re($Delta); # stored in ReDelta.dat
    my $im = Im($Delta); # stored in ImDelta.dat

    # Perform ImDelta.dat clipping to ensure hybridization function (Gamma=-ImDelta) is positive (!)
    if ($im > $clip) {
        $im = -$clip;
    }

    print R "$o $re\n";
    print I "$o $im\n";
}
