#!/usr/bin/env perl
# Compute lattice spectral function (ldos.dat)
# By default it uses a linear grid of 10001 points in [w_min:w_max] defined by resigma.dat and imsigma.dat
# Rok Zitko, rok.zitko@ijs.si, June 2017

use strict;
use warnings;
use FindBin;
use lib $FindBin::Bin;
use Bubble qw(bubble_options chemical_potential parameter run_bubble);

my $T = parameter("T");
$T > 0.0 or die "T must be positive\n";
my $mu = chemical_potential();

my $fn = "DOS.dat";
my @param = (bubble_options(epsabs => "1e-9", epsrel => "1e-8"), "-p", $fn);

# Compute ldos.dat to be compared with imaw.dat
my $output = "ldos.dat";
my $temporary = "$output.tmp.$$";
END { unlink($temporary) if defined($temporary) && -e $temporary; }
run_bubble("-d", "-o", $temporary, @param,
           0, 1, 0, $T, $mu, "resigma.dat", "imsigma.dat");
-s $temporary or die "Bubble did not produce $temporary\n";
rename($temporary, $output) or die "Can't replace $output: $!";
