#!/usr/bin/env perl
# Compute lattice spectral function (dos.dat)
# By default it uses a linear grid of 10000 points in [w_min:w_max] interval defined by resigma.dat and imsigma.dat
# Rok Zitko, rok.zitko@ijs.si, June 2017

use strict;
use warnings;
use Math::Complex;

chomp(my $T = `getparam T param.loop`);

my $fn = "DOS.dat";
my $param = "-p $fn -c 30 -a 1e-8 -r 1e-7 -i 3 -k 6";

# Chemical potential
chomp(my $mu = `cat param.mu`);

# Compute dos.dat to be compared with imaw.dat
system "bubble -d $param 0 1 0 $T $mu resigma.dat imsigma.dat";
