#!/usr/bin/env perl
# Computes kinetic energy
# Rok Zitko, nov 2017
chomp(my $T = `getparam T param.loop`);
($? == 0) or die;

# Chemical potential
chomp(my $mu = `cat param.mu`);
($? == 0) or die;

my $param = "-E -c 30 -a 1e-7 -r 1e-6 -i 3 -k 5";

my $res = `bubble $param -e 1 -p DOS.dat -f 0 1 0 $T $mu resigma.dat imsigma.dat`;
($? == 0) or die;
$res *= 2; # spin!

open(O, ">ekin.dat");
print O "$res\n";
close O;
