#!/usr/bin/env perl
# Computes kinetic energy
# Rok Zitko, nov 2017
chomp(my $T = `getparam T param.loop`);
($? == 0) or die;

# Chemical potential
my $mu_file = defined($ENV{DMFT_MU_FILE}) && length($ENV{DMFT_MU_FILE})
    ? $ENV{DMFT_MU_FILE} : (-s "param.mu.used" ? "param.mu.used" : "param.mu");
open(my $mu_fh, "<", $mu_file) or die "Can't open $mu_file for reading, stopped";
chomp(my $mu = <$mu_fh>);
close($mu_fh);

my $param = "-E -c 30 -a 1e-7 -r 1e-6 -i 3 -k 5";

my $res = `bubble $param -e 1 -p DOS.dat -f 0 1 0 $T $mu resigma.dat imsigma.dat`;
($? == 0) or die;
$res *= 2; # spin!

open(O, ">ekin.dat");
print O "$res\n";
close O;
