#!/usr/bin/env perl
# Generates frequency-independent re/imsigma files for initializing the DMFT loop. 
# Follow this step by running "bandDOS". 
# RZ 2025-2026

use strict;
use warnings;
use File::Path qw(make_path);

my $result_dir = @ARGV ? shift @ARGV : "res";
my $mesh_file = @ARGV ? shift @ARGV : "mesh.dat";
@ARGV and die "Usage: $0 [result_dir [mesh_file]]\n";

my $U = `getparam U1 param.loop`; # Hubbard U
my $nspin = 0.5; # occupancy per spin, half filling is 0.5

my $r = $U * $nspin; # Hartree shift
$r -= 0; # manual tweak

my $i = -0.0001; # Use some negative value.

print "Initializing from constant self-energy. ReSigma=$r ImSigma=$i\n";

-e $mesh_file or die "Error - $mesh_file is required to define the frequency mesh.";

make_path($result_dir) unless -d $result_dir;
-d $result_dir or die "Failed to create $result_dir.";

open(F, "<", $mesh_file) or die;
open(R, ">", "$result_dir/resigma.dat") or die;
open(I, ">", "$result_dir/imsigma.dat") or die;

while(<F>) {
  my ($x, $y) = split;
  print R "$x $r\n";
  print I "$x $i\n";
}
