#!/usr/bin/env perl
# Process a 'data.in' template file: fill in the numerical values,
# diagonalize the Hamiltonian matrices, perform the transformations.
# Rok Zitko, 2009-2019

use strict;
use warnings;
use File::Copy;
use Math::Trig;
use POSIX qw(isfinite);

my $path = "template/";

# Paths to tools used
my $matrix = "matrix";
my $diag = "diag -B";
my $unitary = "unitary -B";

my $verbose = 1;
my $number_pattern = qr/[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?/;

# Split param file into sections
my $fnparam = "param";
open (F, "<$fnparam") or die "Can't open $fnparam.";
my $section = "";
while (<F>) {
    if (/^\[(.*)\]$/) {
        close O if $section ne "";
        $section = $1;
        my $fnout = "$fnparam.$section";
        open (O, ">$fnout") or die "Cant open $fnout.";
    }
    if ($section ne "") {
        # nrgchain receives one resolved Nmax below, including in Tmin mode.
        next if $section eq "param" && /^\s*Nmax\s*=/;
        print O;
    }
}
close O if $section ne "";
close F;

my %solver_params = read_parameters($fnparam);
my $nr = resolve_nmax(\%solver_params);
open(my $chain_param, ">>", "$fnparam.param")
    or die "Can't open $fnparam.param for appending: $!\n";
print {$chain_param} "\nNmax=$nr\n";
close($chain_param) or die "Can't close $fnparam.param: $!\n";

system("scripts/wilson", "$fnparam.param") == 0 or die "wilson failed: $?";

### Translate data.in -> data
my $fnin = "$path/data.in";
open(F, "<$fnin") or die "Can't open $fnin.";

my $fnout = "data";
open(OUT, ">$fnout") or die "Can't open $fnout.";

my $mode = 0; # Current parser mode
my $factor = -1; # Rescale factor for energies
my $smallest = 1e9; # Lowest rescaled energy (Egs=smallest/factor)

my %dim; # Dimensions of invariant subspaces

my $subspaces = -1; # Number of different subspaces
my $Egs = -999;

my $perch = 1;
if (getparam("polarized") eq "true") {
    $perch = 2;
}
my $channels;
my $coefchannels;
my $fctr = 0;

while (<F>) {
    print;

    if (/^#/) {
        if (/^# SCALE\s+(\S+)$/) {
            # Extract the rescale factor
            $factor = 1.0/$1;
        }
        # Copy comments verbatim
        print OUT;
        next;
    }

    if ($mode == 0) {
        if (!/(\d+)\s+(\d+)\s+(\d+)/) { die "Parse error 1: $_"; }
        $channels = $1;
        $coefchannels = $channels * $perch;
        my $impurities = $2;
        $subspaces = $3;
        $impurities = $nr; # override!
        print "ch=$channels coefch=$coefchannels im=$impurities sub=$subspaces\n";
        print OUT "$channels $impurities $subspaces\n";
        $mode = 1;
        next;
    }

    if ($mode == 1) {
        my @buffer;
        my $i;
        for ($i = 1; $i <= $subspaces; $i++) {
            if ($i != 1) { $_ = <F>; }
            if (!/(\S+)\s+(\S+)/) { die "Parse error 2: $_"; }
            my $qnspaces = "$1 $2";
            my $qn = "$1.$2";
            my $size;
            chomp($size = <F>);
            $dim{$qn} = $size; # store size!
            print "[$i] $qn dim=$size\n";
            my $line1;
            chomp($line1 = <F>);
            $line1 =~ /DIAG\s+(\S+)$/;
            my $fn = $1;

            system("$matrix -c$coefchannels param.extra $path/$fn >ham") == 0 or die "matrix failed: $?";
            copy("ham", "ham.$qn");

            ($factor > 0) or die "no factor?";
            system("$diag -q -s $factor -o val -O vec ham") == 0 or die "diag failed: $?";

            my $eig = `cat val`;
            push(@buffer,  [ "$qnspaces\n$size\n", $eig ]);
            if ($eig =~ /^([-0-9.]+)(\s|\n)/) {
                my $min = $1;
                if ($smallest > $min) { $smallest = $min; }
            }
            copy("vec", "vec.$qn");
        }
        $Egs=$smallest/$factor;
        print "E_gs=$Egs\n";

        @buffer = map { $_->[0].subtract($_->[1]) } @buffer;
        print OUT @buffer;

        $mode = 2;
        next;
    }

    if ($mode == 2) {
        if (!/f\s+(\d+)\s+(\d+)/) { die "Parse error 3: $_"; }
        print OUT;
        unitary();
        $fctr++;
        if ($fctr == $channels) {
            $mode = 3;
        }
        next;
    }

    if ($mode == 3) {
        if (!/^e/) { die "Parse error 5: $_"; }
        my $egs = <F>;
        print OUT "e\n$Egs\n";
        $mode = 4;
        next;
    }

    if ($mode == 4) {
        if (/^[zZT]/) { # Discretization tables
            $mode = 5;
            next;
        }
        if (/^[spdvt]/) {
            print OUT;
            unitary();
            next;
        }
        die "Parse error 6: $_";
    }
}

my $adddisc = 1;

if ($adddisc) {
    print OUT "z\n";
    for (my $ch = 1; $ch <= $perch*$channels; $ch++) {
        print OUT "$nr\n";
        my $xi = `cat xi${ch}.dat`;
        print OUT "$xi";
    }
    for (my $ch = 1; $ch <= $perch*$channels; $ch++) {
        print OUT "$nr\n";
        my $zeta = `cat zeta${ch}.dat`;
        print OUT "$zeta";
    }
}

sub subtract
{
    my $vals = shift;
    my @l = split(' ', $vals);
    @l = map { $_-$smallest } @l;
    return "@l\n";
}

sub unitary
{
    chomp(my $nr = <F>);
    print "nr=$nr\n";
    print OUT "$nr\n";
    for (my $i = 1; $i <= $nr; $i++) {
        print "unitary i=$i\n";
        chomp(my $line = <F>);
        if (!($line =~ /(\S+)\s+(\S+)\s+(\S+)\s+(\S+)/)) { die "Parse error 4: $_"; }
        my $qn1spaces = "$1 $2";
        my $qn1 = "$1.$2";
        my $dim1 = $dim{$qn1};
        my $qn2spaces = "$3 $4";
        my $qn2 = "$3.$4";
        my $dim2 = $dim{$qn2};
        print "$qn1 $dim1 $qn2 $dim2\n";
        $line = <F>;
        my $c = substr($line, 0, 1);
        if ($c ne "o") {
            open(O, ">mat") or die "Can't open mat for writing.";
            for (my $n = 1; $n <= $dim1; $n++) {
                print O $line;
                if ($n != $dim1) { $line = <F>; }
            } # for $n
            close(O);
        } else {
            chomp(my $fn = $line);
            -e "$path/$fn" or die "File not found: $fn";
            system("$matrix -c$coefchannels param.extra $path/$fn >mat") == 0 or die "matrix failed: $?";
        }
        my $cmd = "$unitary -l -q -o mat.res vec.$qn1 mat vec.$qn2";
        system($cmd) == 0 or die "unitary failed: $?";
        my $res = `cat mat.res`;
        print OUT "$qn1spaces $qn2spaces\n$res";
   } # for $i
}

my $target_dir = shift;
if (defined($target_dir) && -d $target_dir) {
    system("cp param data $target_dir") == 0 or die;
}

sub getparam
{
    my $keyword = shift;
    my $fn = "param";
    open (G, "<", $fn) or die "Can't open $fn for reading: $!\n";
    while (<G>) {
        if (/^$keyword=(.*)/) {
            return $1;
        }
    }
    close G;
    die "Parsing failure: $keyword not found.";
}

sub read_parameters
{
    my $filename = shift;
    open(my $fh, "<", $filename) or die "Can't open $filename for reading: $!\n";
    my %parameters;
    my $section = "";
    while (<$fh>) {
        chomp;
        s/\r$//;
        if (/^\s*\[([^]]+)\]\s*$/) {
            $section = $1;
            next;
        }
        next if $section ne "param" || /^\s*(?:#|$)/;
        if (/^\s*([^=\s]+)\s*=\s*(.*?)\s*$/) {
            $parameters{$1} = $2;
        }
    }
    close($fh) or die "Can't close $filename: $!\n";
    return %parameters;
}

sub numeric_parameter
{
    my ($parameters, $name, $default) = @_;
    return $default if !exists $parameters->{$name};
    my $text = $parameters->{$name};
    $text =~ /\A$number_pattern\z/
        or die "$name must be a finite number: $text\n";
    my $value = 0.0 + $text;
    isfinite($value) or die "$name must be a finite number: $text\n";
    my $significand = $text;
    $significand =~ s/[eE].*$//;
    $significand =~ s/[+.\-]//g;
    $value != 0.0 || $significand !~ /[1-9]/
        or die "$name must be a finite representable number: $text\n";
    return $value;
}

sub integer_parameter
{
    my ($parameters, $name) = @_;
    my $text = $parameters->{$name};
    $text =~ /\A-?\d+\z/ or die "$name must be an integer: $text\n";
    return $text;
}

sub validated_nmax
{
    my $text = shift;
    $text = "$text";
    $text =~ s/^0+(?=\d)//;
    $text =~ /\A\d{1,3}\z/ && $text >= 1 && $text < 999
        or die "Nmax must be an integer in the range 1..998: $text\n";
    return 0 + $text;
}

sub resolve_nmax
{
    my $parameters = shift;
    my $has_nmax = exists $parameters->{Nmax};
    my $has_tmin = exists $parameters->{Tmin};

    $has_nmax && $has_tmin
        and die "Specify either Nmax or Tmin, not both!\n";

    my $nmax = $has_nmax
        ? integer_parameter($parameters, "Nmax")
        : undef;
    my $tmin = 0.0;

    if (exists $parameters->{T} && exists $parameters->{Tmin_ratio}) {
        my $temperature = numeric_parameter($parameters, "T");
        my $ratio = numeric_parameter($parameters, "Tmin_ratio");
        if ($temperature > 0 && $ratio > 0) {
            $tmin = $temperature * $ratio;
            isfinite($tmin) && $tmin > 0
                or die "T*Tmin_ratio must be a finite representable number\n";
            print "Tmin_ratio ==> Tmin=$tmin\n";
        }
    }

    if ($has_tmin) {
        $tmin = numeric_parameter($parameters, "Tmin");
        print "Tmin=$tmin\n";
    }

    if ($tmin > 0) {
        $nmax = nmax_from_tmin($parameters, $tmin);
        print "Tmin=$tmin ==> Nmax=$nmax\n";
    }

    defined($nmax)
        or die "Specify Nmax, a positive Tmin, or positive T and Tmin_ratio\n";
    return validated_nmax($nmax);
}

sub nmax_from_tmin
{
    my ($parameters, $tmin) = @_;
    my $lambda = numeric_parameter($parameters, "Lambda", 2.0);
    $lambda > 1.0 or die "Lambda must be greater than 1\n";
    my $z = numeric_parameter($parameters, "z", 1.0);
    0.0 < $z && $z <= 1.0 or die "z must satisfy 0 < z <= 1\n";
    my $bandrescale = numeric_parameter($parameters, "bandrescale", 1.0);
    $bandrescale > 0.0 or die "bandrescale must be positive\n";

    my $discretization = exists $parameters->{discretization}
        ? $parameters->{discretization}
        : "Z";
    my $scheme = substr($discretization, 0, 1);
    $scheme eq "C" || $scheme eq "Y" || $scheme eq "Z"
        or die "Unknown discretization: $discretization\n";

    my $prefactor = $scheme eq "Y"
        ? (1.0 + 1.0/$lambda)/2.0
        : (1.0 - 1.0/$lambda)/log($lambda);
    my $sc0 = $prefactor * $lambda**(1.0 - $z);
    my $nmax = 0;
    while (1) {
        my $n = $nmax + 1;
        my $scale = $sc0 * $lambda**(-($n - 1.0)/2.0) * $bandrescale;
        isfinite($scale) or die "Wilson scale is not finite\n";
        last if $scale < $tmin;
        $nmax++;
        $nmax < 999
            or die "Tmin resolves to Nmax >= 999, unsupported by nrginit\n";
    }
    $nmax > 0
        or die "Tmin is above the first Wilson scale and resolves to Nmax=0\n";
    return $nmax;
}

unlink "xi1.dat";
unlink "zeta1.dat";
unlink "theta1.dat";
unlink "val";
unlink "vec";
unlink glob "vec.*";
unlink "mat";
unlink "mat.res";
unlink "ham";
unlink glob "ham.*";
unlink "param.param";
unlink "param.dmft";
unlink "param.extra";
unlink "solverlog";
unlink "solverlogneg";
