#!/usr/bin/env perl
# Run postprocessing scripts

use strict;
use warnings;

my @validation = ("scripts/validate_bare_inputs");
push(@validation, "--require-phi") if -x "scripts/cond.opt-PHI";
system(@validation) == 0 or die "Bare-input validation failed: $?";

$ENV{DMFT_MU_FILE} = "param.mu.used"
    if (!defined($ENV{DMFT_MU_FILE}) || $ENV{DMFT_MU_FILE} eq "")
    && -s "param.mu.used";

if (-x "scripts/bbl") {
    system("scripts/bbl") == 0 or die;
}

if (-x "scripts/dos") {
    system("scripts/dos") == 0 or die;
}

if (-x "scripts/ekin") {
    system("scripts/ekin") == 0 or die;
}

if (-x "scripts/cond.opt-PHI") {
    system("scripts/cond.opt-PHI") == 0 or die;
}

if (-x "scripts/Z") {
    system("scripts/Z --force >Z.dat") == 0 or die;
}

if (-x "scripts/plot.py") {
    system("scripts/plot.py") == 0 or die;
}
