#!/usr/bin/env perl
# Run postprocessing scripts

use strict;
use warnings;

if (-x "scripts/bbl") {
    system("scripts/bbl") == 0 or die;
}

if (-x "scripts/dos") {
    system("scripts/dos") == 0 or die;
}

if (-x "scripts/ekin") {
    system("scripts/ekin") == 0 or die;
}

if (-x "scripts/cond.opt-PHI") {
    system("scripts/cond.opt-PHI") == 0 or die;
}

if (-x "scripts/Z") {
    system("scripts/Z --force >Z.dat") == 0 or die;
}
