#!/usr/bin/env perl
# Calculate real parts of Green's functions
# Rok Zitko, rok.zitko@ijs.si, 2008-2026

use strict;
use warnings;

my $kkexe = "kk";

chdir "res";

my @l = qw( c-imF c-imG c-imI );

my ($in, $out);
foreach (@l) {
    $in = "$_.dat";
    ($out = $in) =~ s/im/re/;
    kk($in, $out);
}

sub kk {
    my ($in, $out) = @_;
    -s $in or die "Input file not found: $in. Stopped";
    system("$kkexe $in $out");
    -s $out or die "Output file not found:$ out. Stopped";
}
