#!/usr/bin/env perl
# Estimate the endpoint-average shift in ReDelta.dat as a diagnostic.
# The DMFT loop does not use this estimate: param.eps is the authoritative
# static shift added during causal reconstruction.
# Rok Zitko, Aug 2026

use strict;
use warnings;

my $file = @ARGV ? shift @ARGV : "ReDelta.dat";
@ARGV and die "Usage: $0 [ReDelta]\n";
-s $file or die;

open my $fh, '<', $file or die "$file: $!";
my ($first, $last);
while (<$fh>) {
    $first //= $_;
    $last = $_;
}
close $fh;
chomp($first, $last) if defined $first;

print "[$first]\n";
print "[$last]\n";

my ($x0, $y0) = split(' ', $first);
my ($x1, $y1) = split(' ', $last);

my $xavg = ($x0+$x1)/2.0;
my $yavg = ($y0+$y1)/2.0;

(abs($xavg) < 1e-8) or die; # symmetry test

print "ReDelta shift=$yavg\n";

open(O, ">param.shift") or die;
print O "$yavg\n";
close(O);
