#!/usr/bin/env perl
# Calculate the self-energy and the spectral function via the self-energy trick
# Assumption: the same mesh is used in all files (Delta.dat and various spectra).
# General approach, for QS symmetry type
# Rok Zitko, rok.zitko@ijs.si, 2008-2026

use strict;
use warnings;
use Math::Complex;

my $result_dir = @ARGV ? shift @ARGV : (-d "res" ? "res" : ".");
my $mesh_file = @ARGV ? shift @ARGV
    : ($result_dir eq "." && -s "mesh.used.dat" ? "mesh.used.dat" : "mesh.dat");
my $mu_file = @ARGV ? shift @ARGV
    : ($result_dir eq "." && -s "param.mu.used" ? "param.mu.used" : "param.mu");
my $customfdm_file = @ARGV ? shift @ARGV : "customfdm.avg";
@ARGV and die "Usage: $0 [result_dir [mesh_file [mu_file [customfdm_file]]]]\n";

# $imclip is the "infinitesimal" clipping value for Im(Sigma), to prevent causality violations
chomp(my $imclip = `getparam clipSigma param.loop`);
if ($imclip eq "") {
    chomp($imclip = `getparam clip param.loop`); # fall back
}
$imclip ne "" or die;
$imclip > 0.0 or die;

print "sigmatrick - imclip=$imclip\n";

-s $mesh_file or die;
my @omega = readcol($mesh_file, 1);

my @imG = readcol("$result_dir/c-imG.dat", 2);
my @reG = readcol("$result_dir/c-reG.dat", 2);
my @imF = readcol("$result_dir/c-imF.dat", 2);
my @reF = readcol("$result_dir/c-reF.dat", 2);
my @imI = readcol("$result_dir/c-imI.dat", 2);
my @reI = readcol("$result_dir/c-reI.dat", 2);

scalar(@omega) == scalar(@imG) or die "ImG mesh mismatch.";
scalar(@omega) == scalar(@reG) or die "ReG mesh mismatch.";
scalar(@omega) == scalar(@imF) or die "ImF mesh mismatch.";
scalar(@omega) == scalar(@reF) or die "ReF mesh mismatch.";
scalar(@omega) == scalar(@imI) or die "ImI mesh mismatch.";
scalar(@omega) == scalar(@reI) or die "ReI mesh mismatch.";

# Hartree shift
open(my $sigmah_fh, "-|", "extractcolumn", $customfdm_file, "SigmaHd")
    or die "Can't run extractcolumn: $!";
my $SigmaH = <$sigmah_fh>;
close($sigmah_fh) or die "extractcolumn failed: $?";
defined $SigmaH or die "SigmaHd not found in $customfdm_file";
chomp($SigmaH);

# Chemical potential
open(my $mu_fh, "<", $mu_file) or die "Can't open $mu_file for reading, stopped";
my $mu = <$mu_fh>;
close($mu_fh);
defined $mu or die "Chemical potential not found in $mu_file";
chomp($mu);
print "mu=$mu\n";

# Note that the required shift is already contained in ReDelta.dat; no shift
# needs to be read from a file!

my $imdelta_file = $result_dir eq "." && -s "ImDelta.used.dat"
    ? "ImDelta.used.dat" : "$result_dir/ImDelta.dat";
my $redelta_file = $result_dir eq "." && -s "ReDelta.used.dat"
    ? "ReDelta.used.dat" : "$result_dir/ReDelta.dat";
my @imdelta = readcol($imdelta_file, 2);
my @redelta = readcol($redelta_file, 2);

scalar(@omega) == scalar(@imdelta) or die "ImDelta mesh mismatch.";
scalar(@omega) == scalar(@redelta) or die "ReDelta mesh mismatch.";

my $selffn = "$result_dir/c-self.dat";
open(SELF, ">$selffn") or die "Can't open $selffn for writing, stopped";

my $imsigma = "$result_dir/imsigma.dat";
open(IM, ">$imsigma") or die "Can't open $imsigma for writing, stopped";

my $resigma = "$result_dir/resigma.dat";
open(RE, ">$resigma") or die "Can't open $resigma for writing, stopped";

my $pi = pi;

my $len = @omega;
for (my $i = 0; $i < $len; $i++) {
  my $o = $omega[$i];
  my $G = $reG[$i] + i * $imG[$i];
  $G = -$pi * $G; # this is now G, the local Green's function
  my $F = $reF[$i] + i * $imF[$i];
  $F = -$pi * $F; # this is now F, the auxiliary Green's function
  my $I = $reI[$i] + i * $imI[$i];
  $I = -$pi * $I; # this s now I, the 2nd auxiliary Green's function

  my $sigma = $SigmaH + $I - $F/$G*$F;
#  my $sigma = $F/$G;

  my $re = Re($sigma);
  my $im = Im($sigma);

  if ($im > -$imclip) {
      $im = -$imclip;
  }
  $im < 0.0 or die; # contract

  print IM "$o $im\n";
  print RE "$o $re\n";

  my $sigma_clipped = $re + i * $im;
  my $delta = $redelta[$i] + i * $imdelta[$i];

  my $gf = 1.0/($o + $mu - $delta - $sigma_clipped);
  my $aw = -1.0/pi * Im($gf);
  $aw > 0.0 or die; # contract

  print SELF "$o $aw\n";

}

# Read a column from a file
sub readcol {
    my ($filename, $column) = @_;
    my @l;
    open(F, "<$filename") or die "Can't open $filename for reading, stopped";
    while (<F>) {
        chomp;
        my $x = (split)[$column-1];
        push(@l, $x);
    }
    close(F);
    @l
};
