#!/usr/bin/env perl
# Calculate the self-energy and the spectral function via the self-energy trick
# Assumption: the same mesh is used in all files (Delta.dat and various spectra).
# General approach, for QS symmetry type
# Rok Zitko, rok.zitko@ijs.si, 2008-2026

use strict;
use warnings;
use Math::Complex;

my $imclip = `getparam clip param.loop` # "infinitesimal" clipping value for Im(Sigma), to prevent causality violations

my $prefix = (-d "res" ? "res" : ".");

my @omega = readcol("mesh.dat", 1);

my @imG = readcol("$prefix/c-imG.dat", 2);
my @reG = readcol("$prefix/c-reG.dat", 2);
my @imF = readcol("$prefix/c-imF.dat", 2);
my @reF = readcol("$prefix/c-reF.dat", 2);
my @imI = readcol("$prefix/c-imI.dat", 2);
my @reI = readcol("$prefix/c-reI.dat", 2);

scalar(@omega) == scalar(@imG) or die "ImG mesh mismatch.";
scalar(@omega) == scalar(@reG) or die "ReG mesh mismatch.";
scalar(@omega) == scalar(@imF) or die "ImF mesh mismatch.";
scalar(@omega) == scalar(@reF) or die "ReF mesh mismatch.";
scalar(@omega) == scalar(@imI) or die "ImI mesh mismatch.";
scalar(@omega) == scalar(@reI) or die "ReI mesh mismatch.";

# Hartree shift
my $SigmaH = `extractcolumn customfdm.avg SigmaHd`;
chomp($SigmaH);

# Chemical potential
chomp(my $mu = `cat param.mu`);
print "mu=$mu\n";

# Note that the required shift is already contained in ReDelta.dat; no shift
# needs to be read from a file!

my @imdelta = readcol("$prefix/ImDelta.dat", 2);
my @redelta = readcol("$prefix/ReDelta.dat", 2);

scalar(@omega) == scalar(@imdelta) or die "ImDelta mesh mismatch.";
scalar(@omega) == scalar(@redelta) or die "ReDelta mesh mismatch.";

my $selffn = "$prefix/c-self.dat";
open(SELF, ">$selffn") or die "Can't open $selffn for writing, stopped";

my $imsigma = "$prefix/imsigma.dat";
open(IM, ">$imsigma") or die "Can't open $imsigma for writing, stopped";

my $resigma = "$prefix/resigma.dat";
open(RE, ">$resigma") or die "Can't open $resigma for writing, stopped";

my $pi = pi;

my $len = @omega;
for (my $i = 0; $i < $len; $i++) {
  my $o = $omega[$i];
  my $G = $reG[$i] + i * $imG[$i];
  $G = -$pi * $G; # this is now G, the local Green's function
  my $F = $reF[$i] + i * $imF[$i];
  $F = -$pi * $F; # this is now F, the auxiliary Green's function
  my $I = $reI[$i] + i * $imI[$i];
  $I = -$pi * $I; # this s now I, the 2nd auxiliary Green's function

  my $sigma = $SigmaH + $I - $F/$G*$F;
#  my $sigma = $F/$G;

  my $delta = i * $imdelta[$i] + $redelta[$i];

  my $gf = 1.0/($o + $mu - $delta - $sigma);
  my $aw = -1.0/pi * Im($gf);

  print SELF "$o $aw\n";

  my $re = Re($sigma);
  my $im = Im($sigma);

  if ($im > -$imclip) {
      $im = -$imclip;
  }

  print IM "$o $im\n";
  print RE "$o $re\n";
}

# Read a column from a file
sub readcol {
    my ($filename, $column) = @_;
    my @l;
    open(F, "<$filename") or die "Can't open $filename for reading, stopped";
    while (<F>) {
        chomp;
        my $x = (split)[$column-1];
        push(@l, $x);
    }
    close(F);
    @l
};
