#!/usr/bin/env perl
# f-sum rule
# This follows from a relation between Phi and DOS for Bethe lattice (and our normalization conventions).
# See also Arsenault, Tremblay PRB, https://doi.org/10.1103/PhysRevB.88.205109
# Rok Zitko, aug 2026

use strict;
use warnings;
use Math::Complex;
use POSIX qw(isfinite);

my $number = qr/[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?/;

open(my $ekin_fh, "<", "ekin.dat") or die "Can't read ekin.dat: $!";
local $/;
my $ekin = <$ekin_fh>;
close($ekin_fh) or die "Can't close ekin.dat: $!";
$ekin =~ /\A\s*($number)\s*\z/ or die "Invalid kinetic energy: $ekin";
$ekin = 0.0 + $1;
isfinite($ekin) && $ekin != 0.0
    or die "Invalid kinetic energy: $ekin\n";

open(my $integ_fh, "-|", "integ", "--interpolation", "steffen",
     "--epsabs", "1e-8", "--epsrel", "1e-6",
     "--workspace-limit", "1000", "--quadrature-rule", "61",
     "--gsl-error-policy", "warn", "cond.opt-PHI.dat")
    or die "Can't run integ: $!";
my $rhoint = <$integ_fh>;
close($integ_fh) or die "integ failed: $?";
defined($rhoint) && $rhoint =~ /\A\s*($number)\s*\z/
    or die "Invalid optical integral: " . (defined($rhoint) ? $rhoint : "<empty>");
$rhoint = 0.0 + $1;
isfinite($rhoint)
    or die "Invalid optical integral: $rhoint\n";

my $ratio = $rhoint/(-$ekin);

my $expected = 3*pi**2/4;

my $r = $ratio/$expected;
isfinite($r) or die "Non-finite sum-rule ratio\n";

print "r=$r\n";
