#!/usr/bin/env perl
# Compute Wilson chain coefficients for the next NRG instance
# Rok Zitko, rok.zitko@ijs.si, Aug 2026

use strict;
use warnings;

my $hybfn = "Delta.dat";
-s $hybfn or die "Hybridisation funcrtion not found.";
system("nrgchain") == 0 or die "nrgchain failed: $?";
-s "xi.dat" && -s "zeta.dat" && -s "theta.dat" or die "Wilson chain coefficients not found.";

system("mv xi.dat xi1.dat") == 0 or die;
system("mv zeta.dat zeta1.dat") == 0 or die;
system("mv theta.dat theta1.dat") == 0 or die;
