#!/usr/bin/env perl
# Compute Wilson chain coefficients for the next NRG instance
# Rok Zitko, rok.zitko@ijs.si, Aug 2026

use strict;
use warnings;

my $hybfn = "Delta.dat";
-s $hybfn or die "Hybridisation funcrtion not found.";
system "nrgchain";
-s "xi.dat" && -s "zeta.dat" && -s "theta.dat" or die "Wilson chain coefficients not found.";

system "mv xi.dat xi1.dat";
system "mv zeta.dat zeta1.dat";
system "mv theta.dat theta1.dat";
