#!/usr/bin/env perl
# Compare files in a reference directory (supplied as the command line argument)
# with the files in the current directory. Resample to compensate for possible different
# discretization grids. Compute differences. Report failure if total integrated errors
# is larger than $limit.
# Rok Zitko, aug 2026

use strict;
use warnings;

my $limit = 1e-4;

my $dir = shift;

-d $dir or die "Usage: $0 reference-directory\n";
chdir $dir or die;

my $sum = 0;

foreach (<*.dat>) {
    -s or next;
    my $filename = $_;
    open(my $input, "<", $filename) or die "Can't read $filename: $!";
    my $count = 0;
    ++$count while defined(my $line = <$input>);
    close($input) or die "Can't close $filename: $!";
    my $diff;
    if ($count > 1) {
        system("resample", "--interpolation", "steffen", "-p", "17",
               "../$filename", $filename, "tmp") == 0
            or die "resample failed for $filename: $?";
        write_difference($filename, "tmp", "diff");
        unlink("tmp");
        $diff = command_output(
            "integ", "--interpolation", "steffen",
            "--epsabs", "1e-10", "--epsrel", "1e-9",
            "--workspace-limit", "1000", "--quadrature-rule", "61",
            "--gsl-error-policy", "fail", "-a", "diff",
        );
    } else {
        $diff = command_output("subtract", $filename, "../$filename");
    }
    chomp($diff);
    $diff =~ /\A[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?\z/
        or die "Invalid difference for $filename: $diff\n";
    $diff = abs(0.0 + $diff);
    $diff <= 1.7976931348623157e308
        or die "Non-finite difference for $filename\n";
    print "$filename $diff\n";
    unlink("diff");
    $sum += $diff;
}

print "Total=$sum\n";

if ($sum > $limit) {
    print "FAILURE.\n";
    exit(1);
} else {
    print "SUCCESS.\n";
    exit(0);
}

sub write_difference {
    my ($first, $second, $output) = @_;
    open(my $input, "-|", "subtracty", $first, $second)
        or die "Can't run subtracty: $!";
    open(my $destination, ">", $output) or die "Can't write $output: $!";
    while (<$input>) {
        print {$destination} $_ or die "Can't write $output: $!";
    }
    close($input) or die "subtracty failed: $?";
    close($destination) or die "Can't close $output: $!";
}

sub command_output {
    my @command = @_;
    open(my $fh, "-|", @command) or die "Can't run $command[0]: $!";
    local $/;
    my $output = <$fh>;
    close($fh) or die "$command[0] failed: $?";
    defined($output) or die "$command[0] produced no output";
    return $output;
}
