#!/usr/bin/env perl
# V2 - RUNNING

use strict;
use warnings;
use Time::HiRes qw(sleep);

sleep(0.5 + rand(3));

my $Tinit = "1"; # as string

my $Tend = 10.0;
my $ratio = 1.1;

open(L, ">log") or die;

# Strategy: find the last converged, use this to initialize a new calculation at updated temperature

my $last_converged;
for (my $T = $Tinit; $T <= $Tend; $T *= $ratio) {
    print "T=$T\n";
    my $dir = "T=$T";
    if (-d "$dir") {
        # Already computed
        if (-e "$dir/CONVERGED") {
            $last_converged = $dir;
        } else { # Continue
            if (!-e "$dir/RUNNING") {
                chdir "$dir";
                system "touch RUNNING";
                system "./START";
                system "rm RUNNING";
                chdir "..";
            }
        }
    } else {
        # New instance
        if (defined($last_converged)) {
            print L "$last_converged $dir\n";
            print "Copying $last_converged -> $dir\n";
            system("cp -r $last_converged $dir") == 0 or die;
            -d $dir or die;
            chdir($dir);
            system("touch RUNNING");
            system("scripts/cleanup keep") == 0 or die;
            system("setparam T $T param.loop") == 0 or die;
            system("./START");
            system("rm RUNNING");
            if (-e "CONVERGED") {
              $last_converged = $dir;
            }
            chdir("..");
        } else {
            die "No place to start from, stopping...";
        }
    }
}
