#!/usr/bin/env perl

use strict;
use warnings;

my $fnin = "rhoMIR.dat";
my $fnout = "rho.dat";

open(O, "|sortnum>rho.dat");

while (<*>) {
    -d or next;
    my $dir = $_;
    /(.*)=(.*)/ or next;
    my $x = $2;
    my $fn = "$dir/$fnin";
    -s $fn or next;
    chomp(my $y = `cat $fn`);
    print O "$x $y\n";
}
