#!/usr/bin/env perl
# Print the normalized first moment of the represented Steffen DOS.

use strict;
use warnings;
use POSIX qw(isfinite);

@ARGV == 1 or die "Usage: $0 DOS.dat\n";
my $dos = $ARGV[0];
my $normalization = integrate("--total", $dos);
my $moment = integrate("--energy-moment", $dos);
$normalization > 0.0 or die "DOS normalization must be positive.\n";
abs($normalization - 1.0) <= 1e-8
    or die "DOS normalization is not one: $normalization\n";
printf "%.17g\n", $moment / $normalization;

sub integrate {
    my ($quantity, $file) = @_;
    open(
        my $fh,
        "-|",
        "integ", "--interpolation", "steffen", $quantity, "--", $file,
    ) or die "Can't run integ: $!";
    local $/;
    my $output = <$fh>;
    close($fh) or die "integ failed for $file\n";
    defined($output) or die "integ returned no result for $file\n";
    $output =~ s/^\s+|\s+$//g;
    $output =~ /\A[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?\z/
        or die "integ returned an invalid result for $file\n";
    my $value = 0.0 + $output;
    isfinite($value) or die "integ returned a non-finite result for $file\n";
    return $value;
}
