#!/bin/bash
set -e

# Ensure that param.eps contains the band energy (average energy of DOS.dat)
# This information about the shift needs to be supplied to the NRG separately,
# because NRG only considers only the imaginary (spectral function) part of the
# hybridization, ImDelta, but not the overall vertical shift contained in ReDelta.
# In other words, if there is a difference between actual ReDelta and kk[ImDelta],
# this needs to be encoded in param.eps.
# Rok Zitko, rok.zitko@ijs.si, Aug 2026

temporary="param.eps-bubble.tmp.$$"
trap 'rm -f "$temporary"' EXIT

bubble --gsl-error-policy fail --workspace-limit 1000 \
  --interpolation steffen --phi-interpolation steffen \
  -k 6 -a 1e-9 -r 1e-8 -s 1e-12 -e 1 -p DOS.dat \
  0 0 0 1e-10 0 DOS.dat DOS.dat >"$temporary"
mv "$temporary" param.eps-bubble
trap - EXIT
