#!/bin/bash
# Ensure that param.eps contains the band energy (average energy of DOS.dat)
# This information about the shift needs to be supplied to the NRG separately,
# because Gamma=-ImDelta determines only the dynamic part. The causal real part
# is defined as kk[ImDelta]+param.eps. For a normalized DOS, this constant is the
# first moment obtained with integrateeps.
# Rok Zitko, rok.zitko@ijs.si, Aug 2026

integrateeps DOS.dat >param.eps
